import type {
  CostBreakdownItem,
  DepartmentWorkforcePlan,
  HiringPlanDraft,
  InternalTalentPool,
  SimulationRecommendation,
  SimulationRoleGap,
  SimulationSkillGap,
  WorkforceAssumption,
  WorkforceTimelineEvent,
} from "./types";

export const manufacturingEmployerProfile = {
  id: "aster-manufacturing",
  name: "Aster Manufacturing Group",
  industry: "Advanced Manufacturing",
  location: "Penang, Malaysia",
  employeeCount: 4800,
  planningHorizon: "2026-2031",
  sites: ["Bayan Lepas Plant", "Kulim Assembly Hub", "Penang HQ"],
  businessContext:
    "A mid-sized electronics manufacturer expanding export volume while older technicians retire and automation changes production roles.",
  operatingModel:
    "High-volume assembly, preventive maintenance, quality analytics, regional supply planning, and B2B export sales.",
};

export const manufacturingWorkforceAssumptions: WorkforceAssumption[] = [
  {
    id: "vacancy-cost",
    label: "Vacancy cost",
    value: "1.35x monthly salary",
    detail: "Includes overtime, contractor backfill, delayed output, and supervisor load.",
  },
  {
    id: "time-to-fill",
    label: "Critical time-to-fill",
    value: "4.6 months",
    detail: "Maintenance and automation roles take longer because local supply is thin.",
  },
  {
    id: "training-yield",
    label: "Upskill conversion",
    value: "68%",
    detail: "Based on internal technical academies converting operators and inspectors into adjacent roles.",
  },
  {
    id: "retirement-risk",
    label: "Retirement trigger",
    value: "Age 55+ within 10 years",
    detail: "Senior maintenance specialists and process engineers carry concentrated knowledge risk.",
  },
  {
    id: "automation-shift",
    label: "Automation displacement",
    value: "0.42 role shift per operator",
    detail: "Operator demand falls, but technician, QA analyst, and automation engineering demand rises.",
  },
];

export const manufacturingDepartments: DepartmentWorkforcePlan[] = [
  {
    id: "production",
    name: "Production",
    site: "Bayan Lepas Plant",
    currentHeadcount: 1850,
    projectedDemand: 1580,
    attritionRisk: 18,
    retirementRisk: 22,
    automationExposure: 74,
    skillReadiness: 61,
    stability: "At Risk",
    avgAge: 39,
    avgTenure: 6.8,
    openRoles: 22,
    retirementEligible10Y: 407,
    pendingResignations: 18,
    flightRiskCount: 151,
    inUpskilling: 126,
    criticalProcesses: ["SMT line operation", "Clean-room assembly", "Lean shift handover"],
    topSkills: ["Machine Operation", "Lean Manufacturing", "Safety Compliance"],
  },
  {
    id: "maintenance",
    name: "Maintenance",
    site: "Kulim Assembly Hub",
    currentHeadcount: 220,
    projectedDemand: 360,
    attritionRisk: 16,
    retirementRisk: 34,
    automationExposure: 28,
    skillReadiness: 48,
    stability: "Critical",
    avgAge: 44,
    avgTenure: 10.2,
    openRoles: 31,
    retirementEligible10Y: 75,
    pendingResignations: 7,
    flightRiskCount: 33,
    inUpskilling: 22,
    criticalProcesses: ["PLC diagnostics", "Preventive maintenance", "Equipment calibration"],
    topSkills: ["PLC Troubleshooting", "Preventive Maintenance", "Robotics"],
  },
  {
    id: "quality",
    name: "Quality Assurance",
    site: "Bayan Lepas Plant",
    currentHeadcount: 310,
    projectedDemand: 390,
    attritionRisk: 11,
    retirementRisk: 18,
    automationExposure: 42,
    skillReadiness: 58,
    stability: "At Risk",
    avgAge: 37,
    avgTenure: 6.1,
    openRoles: 14,
    retirementEligible10Y: 56,
    pendingResignations: 5,
    flightRiskCount: 21,
    inUpskilling: 44,
    criticalProcesses: ["Defect analysis", "ISO audit evidence", "Root cause review"],
    topSkills: ["Root Cause Analysis", "Power BI", "ISO Compliance"],
  },
  {
    id: "supply-chain",
    name: "Supply Chain",
    site: "Penang HQ",
    currentHeadcount: 180,
    projectedDemand: 260,
    attritionRisk: 13,
    retirementRisk: 12,
    automationExposure: 35,
    skillReadiness: 52,
    stability: "At Risk",
    avgAge: 35,
    avgTenure: 4.9,
    openRoles: 11,
    retirementEligible10Y: 22,
    pendingResignations: 4,
    flightRiskCount: 24,
    inUpskilling: 27,
    criticalProcesses: ["Demand planning", "Supplier risk tracking", "Export order allocation"],
    topSkills: ["Forecasting", "Advanced Excel", "Supply Chain Planning"],
  },
  {
    id: "sales",
    name: "Sales",
    site: "Penang HQ",
    currentHeadcount: 210,
    projectedDemand: 245,
    attritionRisk: 14,
    retirementRisk: 8,
    automationExposure: 22,
    skillReadiness: 70,
    stability: "Stable",
    avgAge: 34,
    avgTenure: 4.1,
    openRoles: 9,
    retirementEligible10Y: 17,
    pendingResignations: 5,
    flightRiskCount: 28,
    inUpskilling: 19,
    criticalProcesses: ["Key account planning", "Export pricing", "CRM hygiene"],
    topSkills: ["CRM", "B2B Sales", "Forecasting"],
  },
  {
    id: "marketing",
    name: "Marketing",
    site: "Penang HQ",
    currentHeadcount: 38,
    projectedDemand: 72,
    attritionRisk: 10,
    retirementRisk: 4,
    automationExposure: 26,
    skillReadiness: 46,
    stability: "Growing",
    avgAge: 31,
    avgTenure: 2.8,
    openRoles: 8,
    retirementEligible10Y: 2,
    pendingResignations: 1,
    flightRiskCount: 6,
    inUpskilling: 9,
    criticalProcesses: ["Digital campaign launch", "Distributor enablement", "CRM nurture"],
    topSkills: ["Digital Marketing", "Content Strategy", "CRM"],
  },
  {
    id: "engineering",
    name: "Engineering",
    site: "Kulim Assembly Hub",
    currentHeadcount: 140,
    projectedDemand: 220,
    attritionRisk: 15,
    retirementRisk: 20,
    automationExposure: 20,
    skillReadiness: 50,
    stability: "Critical",
    avgAge: 41,
    avgTenure: 8.7,
    openRoles: 19,
    retirementEligible10Y: 28,
    pendingResignations: 3,
    flightRiskCount: 18,
    inUpskilling: 16,
    criticalProcesses: ["Line automation design", "Fixture engineering", "Yield improvement"],
    topSkills: ["Robotics", "Process Automation", "System Design"],
  },
  {
    id: "digital-transformation",
    name: "Digital Transformation",
    site: "Penang HQ",
    currentHeadcount: 24,
    projectedDemand: 85,
    attritionRisk: 17,
    retirementRisk: 2,
    automationExposure: 12,
    skillReadiness: 44,
    stability: "Critical",
    avgAge: 32,
    avgTenure: 2.3,
    openRoles: 13,
    retirementEligible10Y: 1,
    pendingResignations: 2,
    flightRiskCount: 7,
    inUpskilling: 8,
    criticalProcesses: ["Data platform", "Factory dashboards", "AI adoption support"],
    topSkills: ["SQL", "Power BI", "AI Literacy"],
  },
];

export const manufacturingRoleGaps: SimulationRoleGap[] = [
  {
    role: "Production Operator",
    department: "Production",
    current: 1200,
    projected: 920,
    gap: 280,
    marketSupply: "Abundant",
    prioritySkills: ["Machine Operation", "Safety Compliance", "Lean Manufacturing"],
    recommendedAction: "Mobility",
    avgSalary: 3600,
    timeToFillMonths: 1.4,
    internalReadyNow: 60,
    internalTrainable: 220,
    externalSupplyIndex: 82,
    riskReason: "Automation reduces manual station demand and creates a redeployment pool.",
  },
  {
    role: "Line Supervisor",
    department: "Production",
    current: 155,
    projected: 190,
    gap: -35,
    marketSupply: "Balanced",
    prioritySkills: ["People Management", "Lean Manufacturing", "Quality Control"],
    recommendedAction: "Upskill",
    avgSalary: 6200,
    timeToFillMonths: 2.7,
    internalReadyNow: 14,
    internalTrainable: 46,
    externalSupplyIndex: 58,
    riskReason: "Supervisory demand rises as line complexity increases.",
  },
  {
    role: "Maintenance Technician",
    department: "Maintenance",
    current: 180,
    projected: 310,
    gap: -130,
    marketSupply: "Critical",
    prioritySkills: ["PLC Troubleshooting", "Preventive Maintenance", "Safety Compliance"],
    recommendedAction: "Hire",
    avgSalary: 5400,
    timeToFillMonths: 4.8,
    internalReadyNow: 18,
    internalTrainable: 72,
    externalSupplyIndex: 28,
    riskReason: "Aging specialists hold equipment knowledge while automation raises maintenance load.",
  },
  {
    role: "Automation Engineer",
    department: "Engineering",
    current: 35,
    projected: 120,
    gap: -85,
    marketSupply: "Critical",
    prioritySkills: ["PLC Troubleshooting", "Robotics", "Process Automation"],
    recommendedAction: "Hire",
    avgSalary: 9200,
    timeToFillMonths: 5.2,
    internalReadyNow: 6,
    internalTrainable: 24,
    externalSupplyIndex: 22,
    riskReason: "Automation roadmap outpaces local engineering supply.",
  },
  {
    role: "Quality Inspector",
    department: "Quality Assurance",
    current: 210,
    projected: 165,
    gap: 45,
    marketSupply: "Balanced",
    prioritySkills: ["Quality Control", "ISO Compliance", "Safety Compliance"],
    recommendedAction: "Mobility",
    avgSalary: 4200,
    timeToFillMonths: 1.8,
    internalReadyNow: 24,
    internalTrainable: 36,
    externalSupplyIndex: 64,
    riskReason: "Automated inspection creates surplus capacity that can move into QA analytics.",
  },
  {
    role: "QA Analyst",
    department: "Quality Assurance",
    current: 45,
    projected: 90,
    gap: -45,
    marketSupply: "Scarce",
    prioritySkills: ["Data Analysis", "Root Cause Analysis", "Power BI"],
    recommendedAction: "Upskill",
    avgSalary: 6800,
    timeToFillMonths: 3.6,
    internalReadyNow: 9,
    internalTrainable: 38,
    externalSupplyIndex: 39,
    riskReason: "Defect analytics work grows while manual inspection demand falls.",
  },
  {
    role: "Supply Chain Planner",
    department: "Supply Chain",
    current: 70,
    projected: 115,
    gap: -45,
    marketSupply: "Scarce",
    prioritySkills: ["Forecasting", "Advanced Excel", "Supply Chain Planning"],
    recommendedAction: "Upskill",
    avgSalary: 7200,
    timeToFillMonths: 3.9,
    internalReadyNow: 7,
    internalTrainable: 29,
    externalSupplyIndex: 41,
    riskReason: "Export volatility requires stronger scenario planning and supplier risk coverage.",
  },
  {
    role: "Digital Marketing Specialist",
    department: "Marketing",
    current: 12,
    projected: 35,
    gap: -23,
    marketSupply: "Balanced",
    prioritySkills: ["Digital Marketing", "Content Strategy", "CRM"],
    recommendedAction: "Hire",
    avgSalary: 6200,
    timeToFillMonths: 2.8,
    internalReadyNow: 4,
    internalTrainable: 12,
    externalSupplyIndex: 55,
    riskReason: "Export growth shifts demand from distributor support to digital lead generation.",
  },
  {
    role: "Finance Analyst",
    department: "Finance",
    current: 32,
    projected: 48,
    gap: -16,
    marketSupply: "Balanced",
    prioritySkills: ["Financial Analysis", "Power BI", "Advanced Excel"],
    recommendedAction: "Upskill",
    avgSalary: 6800,
    timeToFillMonths: 2.9,
    internalReadyNow: 5,
    internalTrainable: 14,
    externalSupplyIndex: 57,
    riskReason: "Scenario planning and automation ROI tracking need stronger analytics coverage.",
  },
  {
    role: "HR Operations Executive",
    department: "Human Resources",
    current: 38,
    projected: 28,
    gap: 10,
    marketSupply: "Abundant",
    prioritySkills: ["HRIS", "Employee Support", "Process Documentation"],
    recommendedAction: "Automate",
    avgSalary: 4700,
    timeToFillMonths: 1.9,
    internalReadyNow: 3,
    internalTrainable: 9,
    externalSupplyIndex: 78,
    riskReason: "Workflow automation can absorb repetitive support demand.",
  },
  {
    role: "Data Analyst",
    department: "Digital Transformation",
    current: 10,
    projected: 42,
    gap: -32,
    marketSupply: "Scarce",
    prioritySkills: ["Data Analysis", "SQL", "Power BI"],
    recommendedAction: "Hire",
    avgSalary: 7600,
    timeToFillMonths: 4.1,
    internalReadyNow: 5,
    internalTrainable: 18,
    externalSupplyIndex: 36,
    riskReason: "Factory dashboard adoption creates new demand for analytics support.",
  },
  {
    role: "Senior Equipment Specialist",
    department: "Maintenance",
    current: 42,
    projected: 55,
    gap: -13,
    marketSupply: "Critical",
    prioritySkills: ["Equipment Calibration", "Knowledge Transfer", "Troubleshooting"],
    recommendedAction: "Retain",
    avgSalary: 7800,
    timeToFillMonths: 6.4,
    internalReadyNow: 2,
    internalTrainable: 10,
    externalSupplyIndex: 18,
    riskReason: "Retirement-eligible experts carry undocumented machine-specific knowledge.",
  },
];

export const manufacturingSkillGaps: SimulationSkillGap[] = [
  {
    skill: "PLC Troubleshooting",
    currentReadiness: 34,
    targetReadiness: 72,
    affectedRoles: ["Maintenance Technician", "Automation Engineer", "Senior Equipment Specialist"],
    recommendedProgram: "12-week equipment diagnostics and PLC maintenance bootcamp",
    trainingCostPerPerson: 6200,
    programLengthWeeks: 12,
    availableCohort: 72,
    businessImpact: "Reduces contractor backfill and speeds response to line stoppages.",
  },
  {
    skill: "Power BI",
    currentReadiness: 41,
    targetReadiness: 76,
    affectedRoles: ["QA Analyst", "Finance Analyst", "Supply Chain Planner", "Data Analyst"],
    recommendedProgram: "Analytics dashboard sprint using production and finance datasets",
    trainingCostPerPerson: 2800,
    programLengthWeeks: 8,
    availableCohort: 64,
    businessImpact: "Turns operational data into weekly gap and defect visibility.",
  },
  {
    skill: "Forecasting",
    currentReadiness: 45,
    targetReadiness: 70,
    affectedRoles: ["Supply Chain Planner", "Sales Operations Analyst"],
    recommendedProgram: "Demand planning workshop with sales and procurement scenarios",
    trainingCostPerPerson: 3500,
    programLengthWeeks: 6,
    availableCohort: 29,
    businessImpact: "Improves export order planning and reduces urgent staffing swings.",
  },
  {
    skill: "Digital Marketing",
    currentReadiness: 38,
    targetReadiness: 68,
    affectedRoles: ["Digital Marketing Specialist", "Sales Executive"],
    recommendedProgram: "B2B digital campaign and CRM activation program",
    trainingCostPerPerson: 2400,
    programLengthWeeks: 5,
    availableCohort: 12,
    businessImpact: "Supports export growth without relying only on distributor channels.",
  },
  {
    skill: "Root Cause Analysis",
    currentReadiness: 52,
    targetReadiness: 78,
    affectedRoles: ["QA Analyst", "Line Supervisor", "Quality Inspector"],
    recommendedProgram: "Quality analytics and corrective action simulation",
    trainingCostPerPerson: 3100,
    programLengthWeeks: 7,
    availableCohort: 38,
    businessImpact: "Moves quality work from detection toward prevention.",
  },
  {
    skill: "AI Literacy",
    currentReadiness: 29,
    targetReadiness: 62,
    affectedRoles: ["HR Operations Executive", "Marketing Executive", "Finance Analyst"],
    recommendedProgram: "Practical AI tools for office productivity and reporting",
    trainingCostPerPerson: 1200,
    programLengthWeeks: 4,
    availableCohort: 86,
    businessImpact: "Improves adoption of low-risk automation and reporting workflows.",
  },
];

export const manufacturingInternalTalentPools: InternalTalentPool[] = [
  {
    id: "operators-to-technicians",
    sourceRole: "Production Operator",
    targetRole: "Maintenance Technician",
    department: "Production -> Maintenance",
    employeesReadyNow: 18,
    employeesTrainable: 72,
    readinessScore: 64,
    program: "PLC maintenance bridge program",
    estimatedCost: "RM 446K",
    timeToProductive: "12-16 weeks",
    skillsToClose: ["PLC Troubleshooting", "Preventive Maintenance", "Equipment Safety"],
  },
  {
    id: "inspectors-to-qa-analysts",
    sourceRole: "Quality Inspector",
    targetRole: "QA Analyst",
    department: "Quality Assurance",
    employeesReadyNow: 9,
    employeesTrainable: 38,
    readinessScore: 71,
    program: "Quality analytics academy",
    estimatedCost: "RM 118K",
    timeToProductive: "8-10 weeks",
    skillsToClose: ["Power BI", "Root Cause Analysis", "Data Analysis"],
  },
  {
    id: "planners-to-forecasting",
    sourceRole: "Procurement Executive",
    targetRole: "Supply Chain Planner",
    department: "Supply Chain",
    employeesReadyNow: 7,
    employeesTrainable: 29,
    readinessScore: 66,
    program: "Demand planning sprint",
    estimatedCost: "RM 102K",
    timeToProductive: "6-8 weeks",
    skillsToClose: ["Forecasting", "Scenario Planning", "Supplier Risk"],
  },
  {
    id: "office-to-ai-workflows",
    sourceRole: "HR and Finance Operations",
    targetRole: "Automation-enabled Operations",
    department: "HR / Finance",
    employeesReadyNow: 22,
    employeesTrainable: 86,
    readinessScore: 78,
    program: "AI workflow adoption lab",
    estimatedCost: "RM 103K",
    timeToProductive: "4 weeks",
    skillsToClose: ["AI Literacy", "Prompting", "Process Documentation"],
  },
];

export const manufacturingRecommendations: SimulationRecommendation[] = [
  {
    id: "hire-maintenance-pipeline",
    category: "Hire",
    priority: "Critical",
    title: "Build maintenance technician pipeline",
    problem: "Maintenance faces a projected shortage of 130 technicians while older specialists approach retirement.",
    recommendation: "Hire 58 technicians and convert 72 production operators through a PLC bridge program.",
    estimatedCost: "RM 2.8M",
    timeline: "12 months",
    impact: "High",
    owner: "Head of Manufacturing",
    gapReduction: 130,
    confidence: 82,
    linkedRoles: ["Maintenance Technician", "Senior Equipment Specialist"],
    nextStep: "Open hiring plan and reserve first training cohort.",
  },
  {
    id: "automation-engineer-hiring",
    category: "Hire",
    priority: "Critical",
    title: "Recruit automation engineers",
    problem: "Automation projects increase demand from 35 to 120 engineers by 2031.",
    recommendation: "Open regional sourcing for 45 engineers and convert 24 industrial/process engineers into automation roles.",
    estimatedCost: "RM 4.5M",
    timeline: "18 months",
    impact: "High",
    owner: "Engineering Director",
    gapReduction: 69,
    confidence: 74,
    linkedRoles: ["Automation Engineer"],
    nextStep: "Launch regional search and internal conversion assessment.",
  },
  {
    id: "operator-to-technician-mobility",
    category: "Mobility",
    priority: "High",
    title: "Move production surplus into technical roles",
    problem: "Automation creates a projected surplus of 280 production operators.",
    recommendation: "Select 120 operators for technician, QA, and line supervisor transition tracks.",
    estimatedCost: "RM 1.1M",
    timeline: "9 months",
    impact: "Medium-High",
    owner: "Plant HR Lead",
    gapReduction: 120,
    confidence: 86,
    linkedRoles: ["Production Operator", "Maintenance Technician", "Line Supervisor"],
    nextStep: "View transition pool and shortlist first 40 employees.",
  },
  {
    id: "qa-analytics-upskill",
    category: "Upskill",
    priority: "High",
    title: "Convert inspectors into QA analysts",
    problem: "Inspection work declines while QA analyst demand doubles.",
    recommendation: "Train 38 quality inspectors in root cause analysis, Power BI, and defect trend reporting.",
    estimatedCost: "RM 420K",
    timeline: "6 months",
    impact: "Medium-High",
    owner: "Quality Director",
    gapReduction: 38,
    confidence: 81,
    linkedRoles: ["Quality Inspector", "QA Analyst"],
    nextStep: "Generate learning path and assign evidence projects.",
  },
  {
    id: "supply-chain-forecasting",
    category: "Upskill",
    priority: "High",
    title: "Strengthen supply chain forecasting",
    problem: "Planner demand increases as export orders become more volatile.",
    recommendation: "Run forecasting and scenario planning training for planners, procurement, and sales operations.",
    estimatedCost: "RM 380K",
    timeline: "4 months",
    impact: "Medium-High",
    owner: "Supply Chain Lead",
    gapReduction: 29,
    confidence: 78,
    linkedRoles: ["Supply Chain Planner"],
    nextStep: "Start demand planning cohort with live export data.",
  },
  {
    id: "hr-automation",
    category: "Automate",
    priority: "Medium",
    title: "Automate HR administration",
    problem: "HR operations has high automation exposure and stable future demand.",
    recommendation: "Automate leave workflows, document verification, and repetitive employee support requests.",
    estimatedCost: "RM 620K",
    timeline: "5 months",
    impact: "Medium",
    owner: "People Operations Lead",
    gapReduction: 10,
    confidence: 76,
    linkedRoles: ["HR Operations Executive"],
    nextStep: "View automation plan and identify repetitive workflows.",
  },
  {
    id: "senior-retention",
    category: "Retain",
    priority: "High",
    title: "Retain senior technical specialists",
    problem: "Maintenance and engineering have high retirement risk in specialist roles.",
    recommendation: "Offer phased retirement, mentoring incentives, and knowledge transfer plans for critical experts.",
    estimatedCost: "RM 900K",
    timeline: "12 months",
    impact: "High",
    owner: "CHRO",
    gapReduction: 31,
    confidence: 73,
    linkedRoles: ["Senior Equipment Specialist", "Automation Engineer"],
    nextStep: "Create retention plan for 28 named specialists.",
  },
];

export const manufacturingForecast = [
  { year: "2026", supply: 4800, demand: 4720, net: 80 },
  { year: "2027", supply: 4680, demand: 4860, net: -180 },
  { year: "2028", supply: 4560, demand: 5010, net: -450 },
  { year: "2029", supply: 4440, demand: 5150, net: -710 },
  { year: "2030", supply: 4380, demand: 5290, net: -910 },
  { year: "2031", supply: 4310, demand: 5420, net: -1110 },
];

export const manufacturingCostBreakdown: CostBreakdownItem[] = [
  {
    label: "Lost production capacity",
    value: 8200000,
    detail: "Unfilled maintenance and automation roles slow line recovery and improvement work.",
  },
  {
    label: "Contractor and overtime backfill",
    value: 3400000,
    detail: "External contractors and overtime cover urgent maintenance and QA shortages.",
  },
  {
    label: "Emergency recruitment premium",
    value: 1900000,
    detail: "Critical roles require agencies, signing incentives, and repeated sourcing cycles.",
  },
  {
    label: "Ramp and quality leakage",
    value: 2300000,
    detail: "Late hiring creates longer ramp time and more defect investigation backlog.",
  },
];

export const manufacturingHiringPlanDrafts: HiringPlanDraft[] = [
  {
    id: "maintenance-tech-hiring",
    role: "Maintenance Technician",
    department: "Maintenance",
    targetHires: 58,
    priority: "Critical",
    targetStart: "Q3 2026",
    budget: "RM 2.1M",
    channels: ["TVET partnerships", "Penang experienced hires", "Operator conversion"],
    successMetric: "Close 130-role gap through 58 hires and 72 conversions.",
  },
  {
    id: "automation-engineer-hiring",
    role: "Automation Engineer",
    department: "Engineering",
    targetHires: 45,
    priority: "Critical",
    targetStart: "Q4 2026",
    budget: "RM 4.5M",
    channels: ["Regional sourcing", "Singapore contractor conversion", "Engineering referral campaign"],
    successMetric: "Reach 104 automation engineers by 2030 with internal conversion support.",
  },
  {
    id: "data-analyst-hiring",
    role: "Data Analyst",
    department: "Digital Transformation",
    targetHires: 18,
    priority: "High",
    targetStart: "Q1 2027",
    budget: "RM 1.2M",
    channels: ["Graduate analytics program", "Internal Power BI graduates", "Malaysia tech communities"],
    successMetric: "Support all factory dashboard squads by 2028.",
  },
];

export const manufacturingTimelineEvents: WorkforceTimelineEvent[] = [
  {
    date: "Q2 2026",
    label: "Technician hiring must start",
    severity: "warning",
    detail: "Current time-to-fill means a late start pushes maintenance shortage into 2027 output risk.",
    linkedActionId: "hire-maintenance-pipeline",
  },
  {
    date: "Q1 2027",
    label: "Maintenance gap turns critical",
    severity: "critical",
    detail: "Retirement and attrition combine with automation maintenance load.",
    linkedActionId: "hire-maintenance-pipeline",
  },
  {
    date: "Q4 2028",
    label: "Automation engineer demand peaks",
    severity: "critical",
    detail: "Automation roadmap requires more engineers before operators can be redeployed safely.",
    linkedActionId: "automation-engineer-hiring",
  },
  {
    date: "Q2 2029",
    label: "QA analytics shortage appears",
    severity: "medium",
    detail: "Automated inspection changes quality work from manual checks to data-driven corrective action.",
    linkedActionId: "qa-analytics-upskill",
  },
  {
    date: "2031",
    label: "Full workforce gap reaches -1,110",
    severity: "critical",
    detail: "Without intervention, hiring, retirement, and skill gaps compound into a major capacity risk.",
    linkedActionId: "operator-to-technician-mobility",
  },
];

const totalCostOfInaction = manufacturingCostBreakdown.reduce((sum, item) => sum + item.value, 0);
const totalGapReduction = manufacturingRecommendations.reduce((sum, item) => sum + (item.gapReduction ?? 0), 0);

export const manufacturingSimulationSummary = {
  projectedGap: 1110,
  costOfInaction: totalCostOfInaction,
  resilienceScore: 61,
  highRiskRoles: manufacturingRoleGaps.filter((role) => role.gap < -40).length,
  strongestActionMix: ["Hire", "Upskill", "Mobility"],
  gapReductionPotential: totalGapReduction,
  internalCandidatesReadyNow: manufacturingInternalTalentPools.reduce((sum, pool) => sum + pool.employeesReadyNow, 0),
  internalCandidatesTrainable: manufacturingInternalTalentPools.reduce((sum, pool) => sum + pool.employeesTrainable, 0),
  planCost: 18800000,
};
