import type {
  DepartmentWorkforcePlan,
  SimulationRecommendation,
  SimulationRoleGap,
  SimulationSkillGap,
} from "./types";

export const manufacturingEmployerProfile = {
  id: "aster-manufacturing",
  name: "Aster Manufacturing Group",
  industry: "Advanced Manufacturing",
  location: "Penang, Malaysia",
  employeeCount: 4800,
  planningHorizon: "2026-2031",
  businessContext:
    "A mid-sized electronics manufacturer planning for automation, export growth, retirement risk, and digital go-to-market expansion.",
};

export const manufacturingDepartments: DepartmentWorkforcePlan[] = [
  {
    id: "production",
    name: "Production",
    currentHeadcount: 1850,
    projectedDemand: 1580,
    attritionRisk: 18,
    retirementRisk: 22,
    automationExposure: 74,
    skillReadiness: 61,
    stability: "At Risk",
  },
  {
    id: "maintenance",
    name: "Maintenance",
    currentHeadcount: 220,
    projectedDemand: 360,
    attritionRisk: 16,
    retirementRisk: 34,
    automationExposure: 28,
    skillReadiness: 48,
    stability: "Critical",
  },
  {
    id: "quality",
    name: "Quality Assurance",
    currentHeadcount: 310,
    projectedDemand: 390,
    attritionRisk: 11,
    retirementRisk: 18,
    automationExposure: 42,
    skillReadiness: 58,
    stability: "At Risk",
  },
  {
    id: "supply-chain",
    name: "Supply Chain",
    currentHeadcount: 180,
    projectedDemand: 260,
    attritionRisk: 13,
    retirementRisk: 12,
    automationExposure: 35,
    skillReadiness: 52,
    stability: "At Risk",
  },
  {
    id: "sales",
    name: "Sales",
    currentHeadcount: 210,
    projectedDemand: 245,
    attritionRisk: 14,
    retirementRisk: 8,
    automationExposure: 22,
    skillReadiness: 70,
    stability: "Stable",
  },
  {
    id: "marketing",
    name: "Marketing",
    currentHeadcount: 38,
    projectedDemand: 72,
    attritionRisk: 10,
    retirementRisk: 4,
    automationExposure: 26,
    skillReadiness: 46,
    stability: "Growing",
  },
  {
    id: "finance",
    name: "Finance",
    currentHeadcount: 95,
    projectedDemand: 108,
    attritionRisk: 9,
    retirementRisk: 12,
    automationExposure: 38,
    skillReadiness: 68,
    stability: "Stable",
  },
  {
    id: "hr",
    name: "Human Resources",
    currentHeadcount: 60,
    projectedDemand: 58,
    attritionRisk: 12,
    retirementRisk: 10,
    automationExposure: 55,
    skillReadiness: 63,
    stability: "Stable",
  },
  {
    id: "engineering",
    name: "Engineering",
    currentHeadcount: 140,
    projectedDemand: 220,
    attritionRisk: 15,
    retirementRisk: 20,
    automationExposure: 20,
    skillReadiness: 50,
    stability: "Critical",
  },
  {
    id: "digital-transformation",
    name: "Digital Transformation",
    currentHeadcount: 24,
    projectedDemand: 85,
    attritionRisk: 17,
    retirementRisk: 2,
    automationExposure: 12,
    skillReadiness: 44,
    stability: "Critical",
  },
];

export const manufacturingRoleGaps: SimulationRoleGap[] = [
  {
    role: "Production Operator",
    department: "Production",
    current: 1200,
    projected: 920,
    gap: 280,
    marketSupply: "Abundant",
    prioritySkills: ["Machine Operation", "Safety Compliance", "Lean Manufacturing"],
    recommendedAction: "Mobility",
  },
  {
    role: "Line Supervisor",
    department: "Production",
    current: 155,
    projected: 190,
    gap: -35,
    marketSupply: "Balanced",
    prioritySkills: ["People Management", "Lean Manufacturing", "Quality Control"],
    recommendedAction: "Upskill",
  },
  {
    role: "Maintenance Technician",
    department: "Maintenance",
    current: 180,
    projected: 310,
    gap: -130,
    marketSupply: "Critical",
    prioritySkills: ["PLC Troubleshooting", "Preventive Maintenance", "Safety Compliance"],
    recommendedAction: "Hire",
  },
  {
    role: "Automation Engineer",
    department: "Engineering",
    current: 35,
    projected: 120,
    gap: -85,
    marketSupply: "Critical",
    prioritySkills: ["PLC Troubleshooting", "Robotics", "Process Automation"],
    recommendedAction: "Hire",
  },
  {
    role: "Quality Inspector",
    department: "Quality Assurance",
    current: 210,
    projected: 165,
    gap: 45,
    marketSupply: "Balanced",
    prioritySkills: ["Quality Control", "ISO Compliance", "Safety Compliance"],
    recommendedAction: "Mobility",
  },
  {
    role: "QA Analyst",
    department: "Quality Assurance",
    current: 45,
    projected: 90,
    gap: -45,
    marketSupply: "Scarce",
    prioritySkills: ["Data Analysis", "Root Cause Analysis", "Power BI"],
    recommendedAction: "Upskill",
  },
  {
    role: "Supply Chain Planner",
    department: "Supply Chain",
    current: 70,
    projected: 115,
    gap: -45,
    marketSupply: "Scarce",
    prioritySkills: ["Forecasting", "Advanced Excel", "Supply Chain Planning"],
    recommendedAction: "Upskill",
  },
  {
    role: "Digital Marketing Specialist",
    department: "Marketing",
    current: 12,
    projected: 35,
    gap: -23,
    marketSupply: "Balanced",
    prioritySkills: ["Digital Marketing", "Content Strategy", "CRM"],
    recommendedAction: "Hire",
  },
  {
    role: "Finance Analyst",
    department: "Finance",
    current: 32,
    projected: 48,
    gap: -16,
    marketSupply: "Balanced",
    prioritySkills: ["Financial Analysis", "Power BI", "Advanced Excel"],
    recommendedAction: "Upskill",
  },
  {
    role: "HR Operations Executive",
    department: "Human Resources",
    current: 38,
    projected: 28,
    gap: 10,
    marketSupply: "Abundant",
    prioritySkills: ["HRIS", "Employee Support", "Process Documentation"],
    recommendedAction: "Automate",
  },
  {
    role: "Data Analyst",
    department: "Digital Transformation",
    current: 10,
    projected: 42,
    gap: -32,
    marketSupply: "Scarce",
    prioritySkills: ["Data Analysis", "SQL", "Power BI"],
    recommendedAction: "Hire",
  },
];

export const manufacturingSkillGaps: SimulationSkillGap[] = [
  {
    skill: "PLC Troubleshooting",
    currentReadiness: 34,
    targetReadiness: 72,
    affectedRoles: ["Maintenance Technician", "Automation Engineer"],
    recommendedProgram: "12-week equipment diagnostics and PLC maintenance bootcamp",
  },
  {
    skill: "Power BI",
    currentReadiness: 41,
    targetReadiness: 76,
    affectedRoles: ["QA Analyst", "Finance Analyst", "Supply Chain Planner"],
    recommendedProgram: "Analytics dashboard sprint using production and finance datasets",
  },
  {
    skill: "Forecasting",
    currentReadiness: 45,
    targetReadiness: 70,
    affectedRoles: ["Supply Chain Planner", "Procurement Executive"],
    recommendedProgram: "Demand planning workshop with sales and procurement scenarios",
  },
  {
    skill: "Digital Marketing",
    currentReadiness: 38,
    targetReadiness: 68,
    affectedRoles: ["Digital Marketing Specialist", "Sales Executive"],
    recommendedProgram: "B2B digital campaign and CRM activation program",
  },
  {
    skill: "Root Cause Analysis",
    currentReadiness: 52,
    targetReadiness: 78,
    affectedRoles: ["QA Analyst", "Line Supervisor", "Quality Inspector"],
    recommendedProgram: "Quality analytics and corrective action simulation",
  },
  {
    skill: "AI Literacy",
    currentReadiness: 29,
    targetReadiness: 62,
    affectedRoles: ["HR Operations Executive", "Marketing Executive", "Finance Analyst"],
    recommendedProgram: "Practical AI tools for office productivity and reporting",
  },
];

export const manufacturingRecommendations: SimulationRecommendation[] = [
  {
    id: "hire-maintenance-pipeline",
    category: "Hire",
    priority: "Critical",
    title: "Build maintenance technician pipeline",
    problem: "Maintenance faces a projected shortage of 130 technicians while older specialists approach retirement.",
    recommendation: "Hire 70 technicians and partner with TVET providers for 60 apprenticeship conversions.",
    estimatedCost: "RM 2.8M",
    timeline: "12 months",
    impact: "High",
  },
  {
    id: "automation-engineer-hiring",
    category: "Hire",
    priority: "Critical",
    title: "Recruit automation engineers",
    problem: "Automation projects increase demand from 35 to 120 engineers by 2031.",
    recommendation: "Open regional sourcing for automation engineers and offer conversion paths for industrial engineers.",
    estimatedCost: "RM 4.5M",
    timeline: "18 months",
    impact: "High",
  },
  {
    id: "operator-to-technician-mobility",
    category: "Mobility",
    priority: "High",
    title: "Move production surplus into technical roles",
    problem: "Automation creates a projected surplus of 280 production operators.",
    recommendation: "Select 120 operators for technician, QA, and line supervisor transition tracks.",
    estimatedCost: "RM 1.1M",
    timeline: "9 months",
    impact: "Medium-High",
  },
  {
    id: "qa-analytics-upskill",
    category: "Upskill",
    priority: "High",
    title: "Convert inspectors into QA analysts",
    problem: "Inspection work declines while QA analyst demand doubles.",
    recommendation: "Train 45 quality inspectors in root cause analysis, Power BI, and defect trend reporting.",
    estimatedCost: "RM 420K",
    timeline: "6 months",
    impact: "Medium-High",
  },
  {
    id: "supply-chain-forecasting",
    category: "Upskill",
    priority: "High",
    title: "Strengthen supply chain forecasting",
    problem: "Planner demand increases as export orders become more volatile.",
    recommendation: "Run forecasting and scenario planning training for planners, procurement, and sales operations.",
    estimatedCost: "RM 380K",
    timeline: "4 months",
    impact: "Medium-High",
  },
  {
    id: "hr-automation",
    category: "Automate",
    priority: "Medium",
    title: "Automate HR administration",
    problem: "HR operations has high automation exposure and stable future demand.",
    recommendation: "Automate leave workflows, document verification, and repetitive employee support requests.",
    estimatedCost: "RM 620K",
    timeline: "5 months",
    impact: "Medium",
  },
  {
    id: "senior-retention",
    category: "Retain",
    priority: "High",
    title: "Retain senior technical specialists",
    problem: "Maintenance and engineering have high retirement risk in specialist roles.",
    recommendation: "Offer phased retirement, mentoring incentives, and knowledge transfer plans for critical experts.",
    estimatedCost: "RM 900K",
    timeline: "12 months",
    impact: "High",
  },
];

export const manufacturingForecast = [
  { year: "2026", supply: 4800, demand: 4720, net: 80 },
  { year: "2027", supply: 4680, demand: 4860, net: -180 },
  { year: "2028", supply: 4560, demand: 5010, net: -450 },
  { year: "2029", supply: 4440, demand: 5150, net: -710 },
  { year: "2030", supply: 4380, demand: 5290, net: -910 },
  { year: "2031", supply: 4310, demand: 5420, net: -1110 },
];

export const manufacturingSimulationSummary = {
  projectedGap: 1110,
  costOfInaction: 15800000,
  resilienceScore: 61,
  highRiskRoles: manufacturingRoleGaps.filter((role) => role.gap < -40).length,
  strongestActionMix: ["Hire", "Upskill", "Mobility"],
};
