import type {
  MarketplaceApplication,
  MarketplaceCandidate,
  MarketplaceCompany,
  MarketplaceJob,
  MarketplaceSkill,
  RegionalTalentSignal,
} from "./types";

export const marketplaceCompanies: MarketplaceCompany[] = [
  {
    id: "aster-manufacturing",
    name: "Aster Manufacturing Group",
    industry: "Manufacturing",
    region: "Penang",
    employeeCount: 4800,
    hiringSignal: "Transformation hiring",
    openRoles: 18,
    qualifiedMatches: 42,
    talentSupplyScore: 67,
    competitionLevel: "High",
  },
  {
    id: "maybank",
    name: "Maybank",
    industry: "Banking",
    region: "Klang Valley",
    employeeCount: 43000,
    hiringSignal: "Steady hiring",
    openRoles: 34,
    qualifiedMatches: 96,
    talentSupplyScore: 78,
    competitionLevel: "High",
  },
  {
    id: "airasia",
    name: "AirAsia",
    industry: "Aviation",
    region: "Klang Valley",
    employeeCount: 21000,
    hiringSignal: "Rapid growth",
    openRoles: 22,
    qualifiedMatches: 55,
    talentSupplyScore: 71,
    competitionLevel: "Medium",
  },
  {
    id: "sunway-group",
    name: "Sunway Group",
    industry: "Construction",
    region: "Klang Valley",
    employeeCount: 16000,
    hiringSignal: "Steady hiring",
    openRoles: 16,
    qualifiedMatches: 38,
    talentSupplyScore: 74,
    competitionLevel: "Medium",
  },
  {
    id: "top-glove",
    name: "Top Glove",
    industry: "Healthcare",
    region: "Klang Valley",
    employeeCount: 22000,
    hiringSignal: "Selective hiring",
    openRoles: 12,
    qualifiedMatches: 29,
    talentSupplyScore: 62,
    competitionLevel: "Medium",
  },
  {
    id: "grab",
    name: "Grab Malaysia",
    industry: "Technology",
    region: "Klang Valley",
    employeeCount: 9000,
    hiringSignal: "Transformation hiring",
    openRoles: 28,
    qualifiedMatches: 73,
    talentSupplyScore: 69,
    competitionLevel: "High",
  },
  {
    id: "telekom-malaysia",
    name: "Telekom Malaysia",
    industry: "Telecommunications",
    region: "Klang Valley",
    employeeCount: 20000,
    hiringSignal: "Transformation hiring",
    openRoles: 20,
    qualifiedMatches: 51,
    talentSupplyScore: 72,
    competitionLevel: "Medium",
  },
  {
    id: "gamuda",
    name: "Gamuda",
    industry: "Construction",
    region: "Klang Valley",
    employeeCount: 6000,
    hiringSignal: "Rapid growth",
    openRoles: 15,
    qualifiedMatches: 33,
    talentSupplyScore: 65,
    competitionLevel: "Medium",
  },
  {
    id: "shopee",
    name: "Shopee Malaysia",
    industry: "Retail",
    region: "Klang Valley",
    employeeCount: 7000,
    hiringSignal: "Rapid growth",
    openRoles: 31,
    qualifiedMatches: 88,
    talentSupplyScore: 76,
    competitionLevel: "High",
  },
  {
    id: "petronas",
    name: "Petronas Digital",
    industry: "Energy",
    region: "Klang Valley",
    employeeCount: 48000,
    hiringSignal: "Transformation hiring",
    openRoles: 25,
    qualifiedMatches: 61,
    talentSupplyScore: 70,
    competitionLevel: "High",
  },
];

export const marketplaceSkills: MarketplaceSkill[] = [
  {
    id: "power-bi",
    name: "Power BI",
    category: "Digital",
    demandScore: 88,
    supplyScore: 54,
    growthRate: 24,
    relatedRoles: ["Data Analyst", "Finance Analyst", "Supply Chain Planner"],
  },
  {
    id: "excel",
    name: "Advanced Excel",
    category: "Business",
    demandScore: 82,
    supplyScore: 72,
    growthRate: 10,
    relatedRoles: ["Finance Associate", "Operations Executive", "Procurement Executive"],
  },
  {
    id: "communication",
    name: "Communication",
    category: "Soft Skill",
    demandScore: 90,
    supplyScore: 68,
    growthRate: 8,
    relatedRoles: ["Marketing Executive", "HR Executive", "Sales Executive"],
  },
  {
    id: "ai-literacy",
    name: "AI Literacy",
    category: "Digital",
    demandScore: 84,
    supplyScore: 38,
    growthRate: 39,
    relatedRoles: ["Marketing Executive", "HR Executive", "Business Analyst"],
  },
  {
    id: "data-analysis",
    name: "Data Analysis",
    category: "Digital",
    demandScore: 91,
    supplyScore: 49,
    growthRate: 31,
    relatedRoles: ["Data Analyst", "QA Analyst", "Business Analyst"],
  },
  {
    id: "digital-marketing",
    name: "Digital Marketing",
    category: "Digital",
    demandScore: 79,
    supplyScore: 57,
    growthRate: 22,
    relatedRoles: ["Marketing Executive", "Growth Associate", "Content Strategist"],
  },
  {
    id: "supply-chain-planning",
    name: "Supply Chain Planning",
    category: "Operations",
    demandScore: 81,
    supplyScore: 45,
    growthRate: 18,
    relatedRoles: ["Supply Chain Planner", "Logistics Coordinator", "Procurement Executive"],
  },
  {
    id: "plc-troubleshooting",
    name: "PLC Troubleshooting",
    category: "Technical",
    demandScore: 86,
    supplyScore: 34,
    growthRate: 27,
    relatedRoles: ["Maintenance Technician", "Automation Engineer", "Industrial Engineer"],
  },
  {
    id: "financial-analysis",
    name: "Financial Analysis",
    category: "Business",
    demandScore: 77,
    supplyScore: 63,
    growthRate: 12,
    relatedRoles: ["Finance Associate", "Risk Analyst", "Commercial Analyst"],
  },
  {
    id: "sustainability-reporting",
    name: "Sustainability Reporting",
    category: "Compliance",
    demandScore: 73,
    supplyScore: 31,
    growthRate: 35,
    relatedRoles: ["Sustainability Analyst", "Compliance Executive", "ESG Associate"],
  },
];

export const marketplaceJobs: MarketplaceJob[] = [
  {
    id: "job-001",
    companyId: "aster-manufacturing",
    title: "Maintenance Technician",
    department: "Maintenance",
    industry: "Manufacturing",
    region: "Penang",
    workStyle: "On-site",
    salaryRange: [3200, 5200],
    status: "open",
    requiredSkills: ["PLC Troubleshooting", "Preventive Maintenance", "Safety Compliance"],
    niceToHaveSkills: ["Power BI", "Lean Manufacturing"],
    applicants: 24,
    qualifiedMatches: 7,
    urgency: "Critical",
    postedDaysAgo: 6,
  },
  {
    id: "job-002",
    companyId: "aster-manufacturing",
    title: "Digital Marketing Specialist",
    department: "Marketing",
    industry: "Manufacturing",
    region: "Penang",
    workStyle: "Hybrid",
    salaryRange: [3800, 6500],
    status: "open",
    requiredSkills: ["Digital Marketing", "Content Strategy", "Data Analysis"],
    niceToHaveSkills: ["AI Literacy", "CRM"],
    applicants: 42,
    qualifiedMatches: 16,
    urgency: "High",
    postedDaysAgo: 9,
  },
  {
    id: "job-003",
    companyId: "maybank",
    title: "Finance Associate",
    department: "Finance",
    industry: "Banking",
    region: "Klang Valley",
    workStyle: "Hybrid",
    salaryRange: [3600, 5800],
    status: "open",
    requiredSkills: ["Advanced Excel", "Financial Analysis", "Communication"],
    niceToHaveSkills: ["Power BI", "Risk Analysis"],
    applicants: 86,
    qualifiedMatches: 31,
    urgency: "Medium",
    postedDaysAgo: 12,
  },
  {
    id: "job-004",
    companyId: "airasia",
    title: "Customer Experience Executive",
    department: "Customer Experience",
    industry: "Aviation",
    region: "Klang Valley",
    workStyle: "Hybrid",
    salaryRange: [3300, 5200],
    status: "open",
    requiredSkills: ["Communication", "CRM", "Problem Solving"],
    niceToHaveSkills: ["Data Analysis", "Bahasa Malaysia"],
    applicants: 64,
    qualifiedMatches: 22,
    urgency: "High",
    postedDaysAgo: 4,
  },
  {
    id: "job-005",
    companyId: "sunway-group",
    title: "Sustainability Analyst",
    department: "Corporate Strategy",
    industry: "Construction",
    region: "Klang Valley",
    workStyle: "Hybrid",
    salaryRange: [4200, 7000],
    status: "open",
    requiredSkills: ["Sustainability Reporting", "Data Analysis", "Communication"],
    niceToHaveSkills: ["Power BI", "Project Management"],
    applicants: 38,
    qualifiedMatches: 9,
    urgency: "High",
    postedDaysAgo: 15,
  },
  {
    id: "job-006",
    companyId: "grab",
    title: "Data Analyst",
    department: "Marketplace Operations",
    industry: "Technology",
    region: "Klang Valley",
    workStyle: "Hybrid",
    salaryRange: [4800, 8500],
    status: "open",
    requiredSkills: ["Data Analysis", "SQL", "Power BI"],
    niceToHaveSkills: ["Python", "Experiment Design"],
    applicants: 93,
    qualifiedMatches: 28,
    urgency: "Critical",
    postedDaysAgo: 3,
  },
  {
    id: "job-007",
    companyId: "telekom-malaysia",
    title: "Cybersecurity Analyst",
    department: "Security Operations",
    industry: "Telecommunications",
    region: "Klang Valley",
    workStyle: "Hybrid",
    salaryRange: [5200, 9200],
    status: "open",
    requiredSkills: ["Cybersecurity Basics", "Incident Response", "Communication"],
    niceToHaveSkills: ["Cloud Security", "Python"],
    applicants: 41,
    qualifiedMatches: 10,
    urgency: "Critical",
    postedDaysAgo: 8,
  },
  {
    id: "job-008",
    companyId: "shopee",
    title: "Growth Marketing Executive",
    department: "Marketing",
    industry: "Retail",
    region: "Klang Valley",
    workStyle: "Hybrid",
    salaryRange: [4200, 7200],
    status: "open",
    requiredSkills: ["Digital Marketing", "Data Analysis", "Communication"],
    niceToHaveSkills: ["SQL", "A/B Testing"],
    applicants: 78,
    qualifiedMatches: 26,
    urgency: "High",
    postedDaysAgo: 5,
  },
  {
    id: "job-009",
    companyId: "gamuda",
    title: "Civil Engineer",
    department: "Project Delivery",
    industry: "Construction",
    region: "Johor",
    workStyle: "On-site",
    salaryRange: [4000, 6800],
    status: "open",
    requiredSkills: ["Project Management", "Safety Compliance", "Communication"],
    niceToHaveSkills: ["BIM", "Cost Control"],
    applicants: 33,
    qualifiedMatches: 12,
    urgency: "Medium",
    postedDaysAgo: 18,
  },
  {
    id: "job-010",
    companyId: "petronas",
    title: "Business Analyst",
    department: "Digital Transformation",
    industry: "Energy",
    region: "Klang Valley",
    workStyle: "Hybrid",
    salaryRange: [5000, 8800],
    status: "open",
    requiredSkills: ["Data Analysis", "Stakeholder Management", "AI Literacy"],
    niceToHaveSkills: ["Power BI", "Process Mapping"],
    applicants: 69,
    qualifiedMatches: 21,
    urgency: "High",
    postedDaysAgo: 11,
  },
];

export const marketplaceCandidates: MarketplaceCandidate[] = [
  {
    id: "candidate-001",
    name: "Aina Rahman",
    level: "Graduate",
    region: "Klang Valley",
    degree: "Bachelor of Business Analytics",
    targetRoles: ["Data Analyst", "Business Analyst"],
    skills: ["Data Analysis", "Power BI", "Advanced Excel", "Communication"],
    expectedSalary: 3800,
    availability: "Immediate",
    employabilityScore: 88,
  },
  {
    id: "candidate-002",
    name: "Jason Lee",
    level: "Junior",
    region: "Penang",
    degree: "Diploma in Mechatronics",
    targetRoles: ["Maintenance Technician", "Automation Engineer"],
    skills: ["PLC Troubleshooting", "Preventive Maintenance", "Safety Compliance"],
    expectedSalary: 3600,
    availability: "2 weeks",
    employabilityScore: 82,
  },
  {
    id: "candidate-003",
    name: "Nurul Izzah",
    level: "Graduate",
    region: "Johor",
    degree: "Bachelor of Marketing",
    targetRoles: ["Digital Marketing Specialist", "Growth Marketing Executive"],
    skills: ["Digital Marketing", "Content Strategy", "Communication", "AI Literacy"],
    expectedSalary: 3400,
    availability: "Immediate",
    employabilityScore: 84,
  },
  {
    id: "candidate-004",
    name: "Daniel Tan",
    level: "Mid-level",
    region: "Klang Valley",
    degree: "Bachelor of Computer Science",
    targetRoles: ["Cybersecurity Analyst", "Data Analyst"],
    skills: ["Cybersecurity Basics", "Python", "SQL", "Incident Response"],
    expectedSalary: 6200,
    availability: "1 month",
    employabilityScore: 91,
  },
  {
    id: "candidate-005",
    name: "Priya Nair",
    level: "Junior",
    region: "Perak",
    degree: "Bachelor of Finance",
    targetRoles: ["Finance Associate", "Commercial Analyst"],
    skills: ["Advanced Excel", "Financial Analysis", "Communication"],
    expectedSalary: 3600,
    availability: "Immediate",
    employabilityScore: 79,
  },
  {
    id: "candidate-006",
    name: "Amir Hakim",
    level: "Graduate",
    region: "Sabah",
    degree: "Bachelor of Logistics",
    targetRoles: ["Supply Chain Planner", "Logistics Coordinator"],
    skills: ["Supply Chain Planning", "Advanced Excel", "Communication"],
    expectedSalary: 3300,
    availability: "Immediate",
    employabilityScore: 76,
  },
  {
    id: "candidate-007",
    name: "Mei Ling Wong",
    level: "Junior",
    region: "Sarawak",
    degree: "Bachelor of Environmental Management",
    targetRoles: ["Sustainability Analyst", "Compliance Executive"],
    skills: ["Sustainability Reporting", "Data Analysis", "Communication"],
    expectedSalary: 3700,
    availability: "2 weeks",
    employabilityScore: 81,
  },
  {
    id: "candidate-008",
    name: "Farhan Zulkifli",
    level: "Mid-level",
    region: "Penang",
    degree: "Bachelor of Industrial Engineering",
    targetRoles: ["Industrial Engineer", "Automation Engineer"],
    skills: ["Lean Manufacturing", "PLC Troubleshooting", "Data Analysis", "Project Management"],
    expectedSalary: 5600,
    availability: "1 month",
    employabilityScore: 87,
  },
];

export const marketplaceApplications: MarketplaceApplication[] = [
  { id: "app-001", candidateId: "candidate-002", jobId: "job-001", status: "shortlisted", matchScore: 91, appliedDaysAgo: 3 },
  { id: "app-002", candidateId: "candidate-003", jobId: "job-002", status: "reviewed", matchScore: 86, appliedDaysAgo: 5 },
  { id: "app-003", candidateId: "candidate-005", jobId: "job-003", status: "interviewing", matchScore: 82, appliedDaysAgo: 7 },
  { id: "app-004", candidateId: "candidate-001", jobId: "job-006", status: "shortlisted", matchScore: 89, appliedDaysAgo: 2 },
  { id: "app-005", candidateId: "candidate-004", jobId: "job-007", status: "submitted", matchScore: 88, appliedDaysAgo: 1 },
  { id: "app-006", candidateId: "candidate-007", jobId: "job-005", status: "reviewed", matchScore: 84, appliedDaysAgo: 6 },
  { id: "app-007", candidateId: "candidate-006", jobId: "job-001", status: "submitted", matchScore: 64, appliedDaysAgo: 4 },
  { id: "app-008", candidateId: "candidate-008", jobId: "job-001", status: "interviewing", matchScore: 93, appliedDaysAgo: 8 },
  { id: "app-009", candidateId: "candidate-001", jobId: "job-010", status: "reviewed", matchScore: 85, appliedDaysAgo: 9 },
  { id: "app-010", candidateId: "candidate-003", jobId: "job-008", status: "shortlisted", matchScore: 90, appliedDaysAgo: 2 },
];

export const regionalTalentSignals: RegionalTalentSignal[] = [
  {
    region: "Klang Valley",
    candidateSupply: 18400,
    employerDemand: 21300,
    averageMatchScore: 74,
    strongestSkills: ["Advanced Excel", "Communication", "Financial Analysis"],
    shortageRoles: ["Cybersecurity Analyst", "Data Analyst", "Sustainability Analyst"],
  },
  {
    region: "Penang",
    candidateSupply: 6200,
    employerDemand: 7800,
    averageMatchScore: 69,
    strongestSkills: ["PLC Troubleshooting", "Lean Manufacturing", "Safety Compliance"],
    shortageRoles: ["Maintenance Technician", "Automation Engineer", "Supply Chain Planner"],
  },
  {
    region: "Johor",
    candidateSupply: 5400,
    employerDemand: 5100,
    averageMatchScore: 71,
    strongestSkills: ["Project Management", "Communication", "Operations"],
    shortageRoles: ["Civil Engineer", "Logistics Coordinator", "QA Analyst"],
  },
  {
    region: "Sabah",
    candidateSupply: 3100,
    employerDemand: 2200,
    averageMatchScore: 66,
    strongestSkills: ["Communication", "Operations", "Customer Service"],
    shortageRoles: ["Data Analyst", "Digital Marketing Specialist"],
  },
  {
    region: "Sarawak",
    candidateSupply: 2900,
    employerDemand: 2100,
    averageMatchScore: 67,
    strongestSkills: ["Sustainability Reporting", "Operations", "Communication"],
    shortageRoles: ["Compliance Executive", "Business Analyst"],
  },
];

export const marketplaceSummary = {
  totalEmployers: marketplaceCompanies.length,
  totalOpenRoles: marketplaceJobs.filter((job) => job.status === "open").length,
  totalCandidates: marketplaceCandidates.length,
  totalApplications: marketplaceApplications.length,
  platformTalentSupplyScore: Math.round(
    marketplaceCompanies.reduce((sum, company) => sum + company.talentSupplyScore, 0) / marketplaceCompanies.length
  ),
  mostInDemandSkills: marketplaceSkills
    .slice()
    .sort((a, b) => b.demandScore - a.demandScore)
    .slice(0, 5)
    .map((skill) => skill.name),
};
