-- Run this in Supabase SQL Editor before pointing the hosted backend at Supabase.
-- The backend uses Supabase Auth for passwords and these public tables for app data.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  supabase_user_id uuid unique references auth.users(id) on delete cascade,
  email text not null unique,
  password_hash text,
  role text not null check (role in ('employee', 'employer', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.employee_profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  full_name text not null,
  location text,
  target_role text,
  experience_years integer not null default 0,
  skills_json jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.employer_profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  company_name text not null,
  industry text,
  company_size integer,
  location text,
  created_at timestamptz not null default now()
);

create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  employer_id bigint not null references public.employer_profiles(id) on delete cascade,
  name text not null,
  unique (employer_id, name)
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  employer_id bigint not null references public.employer_profiles(id) on delete cascade,
  department_id bigint references public.departments(id) on delete set null,
  title text not null,
  description text not null,
  required_skills_json jsonb not null default '[]'::jsonb,
  work_style text not null default 'Hybrid',
  location text,
  salary_min integer,
  salary_max integer,
  status text not null default 'draft' check (status in ('draft', 'open', 'closed')),
  created_at timestamptz not null default now()
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  employee_id bigint not null references public.employee_profiles(id) on delete cascade,
  status text not null default 'submitted' check (
    status in ('submitted', 'reviewing', 'interview', 'offered', 'rejected', 'withdrawn')
  ),
  match_score double precision not null default 0,
  created_at timestamptz not null default now(),
  unique (job_id, employee_id)
);

create table if not exists public.simulations (
  id bigint generated by default as identity primary key,
  employer_id bigint references public.employer_profiles(id) on delete set null,
  name text not null,
  input_json jsonb not null,
  result_json jsonb not null,
  model_version text not null,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.employee_profiles enable row level security;
alter table public.employer_profiles enable row level security;
alter table public.departments enable row level security;
alter table public.jobs enable row level security;
alter table public.applications enable row level security;
alter table public.simulations enable row level security;
