-- Career GPS Phase 1: Supabase database foundation.
-- Non-destructive migration: creates new tables, indexes, RLS policies, and illustrative seed data only.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_employee_profile_owner(profile_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.employee_profiles ep
    join public.users u on u.id = ep.user_id
    where ep.id = profile_id
      and u.supabase_user_id = auth.uid()
  );
$$;

create table if not exists public.occupations (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  family text not null,
  description text,
  seniority_level text,
  source_label text not null default 'illustrative_seed',
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.occupation_skills (
  id bigint generated by default as identity primary key,
  occupation_id bigint not null references public.occupations(id) on delete cascade,
  skill_name text not null,
  skill_type text not null default 'required' check (skill_type in ('required', 'preferred', 'optional')),
  proficiency_level text not null default 'foundation' check (
    proficiency_level in ('foundation', 'intermediate', 'advanced')
  ),
  priority integer not null default 3 check (priority between 1 and 5),
  source_label text not null default 'illustrative_seed',
  created_at timestamptz not null default now(),
  unique (occupation_id, skill_name)
);

create table if not exists public.career_transitions (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  from_occupation_id bigint references public.occupations(id) on delete set null,
  to_occupation_id bigint not null references public.occupations(id) on delete cascade,
  title text not null,
  path_family text not null,
  difficulty text not null default 'moderate' check (difficulty in ('low', 'moderate', 'high')),
  estimated_months integer not null check (estimated_months > 0),
  rationale text,
  source_label text not null default 'illustrative_seed',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.career_north_star_settings (
  id bigint generated by default as identity primary key,
  employee_profile_id bigint not null unique references public.employee_profiles(id) on delete cascade,
  target_occupation_id bigint references public.occupations(id) on delete set null,
  target_role text,
  headline text,
  motivation text,
  target_timeline_months integer check (target_timeline_months is null or target_timeline_months > 0),
  status text not null default 'active' check (status in ('active', 'paused', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.career_preferences (
  id bigint generated by default as identity primary key,
  employee_profile_id bigint not null unique references public.employee_profiles(id) on delete cascade,
  preferred_locations_json jsonb not null default '[]'::jsonb,
  preferred_work_styles_json jsonb not null default '[]'::jsonb,
  preferred_industries_json jsonb not null default '[]'::jsonb,
  salary_min integer check (salary_min is null or salary_min >= 0),
  salary_currency text not null default 'MYR',
  open_to_relocation boolean not null default false,
  open_to_remote boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.career_priority_weights (
  id bigint generated by default as identity primary key,
  employee_profile_id bigint not null references public.employee_profiles(id) on delete cascade,
  weight_key text not null,
  weight_value numeric(5, 2) not null check (weight_value >= 0 and weight_value <= 1),
  label text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (employee_profile_id, weight_key)
);

create table if not exists public.career_constraints (
  id bigint generated by default as identity primary key,
  employee_profile_id bigint not null references public.employee_profiles(id) on delete cascade,
  constraint_type text not null,
  label text not null,
  constraint_value_json jsonb not null default '{}'::jsonb,
  is_blocking boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.career_roadmaps (
  id bigint generated by default as identity primary key,
  employee_profile_id bigint not null references public.employee_profiles(id) on delete cascade,
  north_star_setting_id bigint references public.career_north_star_settings(id) on delete set null,
  target_occupation_id bigint references public.occupations(id) on delete set null,
  title text not null,
  summary text,
  status text not null default 'draft' check (status in ('draft', 'active', 'completed', 'archived')),
  current_version integer not null default 1 check (current_version > 0),
  readiness_score_snapshot numeric(5, 2) check (
    readiness_score_snapshot is null or (readiness_score_snapshot >= 0 and readiness_score_snapshot <= 100)
  ),
  fit_score_snapshot numeric(5, 2) check (
    fit_score_snapshot is null or (fit_score_snapshot >= 0 and fit_score_snapshot <= 100)
  ),
  scoring_version text not null default 'not_scored_phase_1',
  source_label text not null default 'user_or_system_created',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.career_routes (
  id bigint generated by default as identity primary key,
  roadmap_id bigint not null references public.career_roadmaps(id) on delete cascade,
  route_type text not null,
  title text not null,
  summary text,
  sequence integer not null check (sequence > 0),
  estimated_months integer check (estimated_months is null or estimated_months > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (roadmap_id, sequence)
);

create table if not exists public.roadmap_milestones (
  id bigint generated by default as identity primary key,
  route_id bigint not null references public.career_routes(id) on delete cascade,
  title text not null,
  description text,
  sequence integer not null check (sequence > 0),
  duration_weeks integer check (duration_weeks is null or duration_weeks > 0),
  focus_skill_name text,
  status text not null default 'planned' check (status in ('planned', 'in_progress', 'completed', 'skipped')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (route_id, sequence)
);

create table if not exists public.milestone_actions (
  id bigint generated by default as identity primary key,
  milestone_id bigint not null references public.roadmap_milestones(id) on delete cascade,
  action_type text not null default 'learning' check (
    action_type in ('learning', 'project', 'application', 'networking', 'assessment', 'reflection')
  ),
  title text not null,
  description text,
  sequence integer not null check (sequence > 0),
  estimated_hours numeric(6, 2) check (estimated_hours is null or estimated_hours >= 0),
  resource_url text,
  status text not null default 'planned' check (status in ('planned', 'in_progress', 'completed', 'skipped')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (milestone_id, sequence)
);

create table if not exists public.roadmap_score_components (
  id bigint generated by default as identity primary key,
  roadmap_id bigint not null references public.career_roadmaps(id) on delete cascade,
  component_key text not null,
  label text not null,
  score numeric(5, 2) check (score is null or (score >= 0 and score <= 100)),
  weight numeric(5, 2) check (weight is null or (weight >= 0 and weight <= 1)),
  explanation text,
  source_label text not null default 'not_scored_phase_1',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (roadmap_id, component_key)
);

create table if not exists public.roadmap_progress (
  id bigint generated by default as identity primary key,
  employee_profile_id bigint not null references public.employee_profiles(id) on delete cascade,
  roadmap_id bigint not null references public.career_roadmaps(id) on delete cascade,
  milestone_id bigint references public.roadmap_milestones(id) on delete cascade,
  action_id bigint references public.milestone_actions(id) on delete cascade,
  status text not null default 'not_started' check (
    status in ('not_started', 'in_progress', 'completed', 'skipped')
  ),
  progress_percent numeric(5, 2) not null default 0 check (progress_percent >= 0 and progress_percent <= 100),
  completed_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (milestone_id is not null or action_id is not null)
);

create unique index if not exists roadmap_progress_unique_milestone
  on public.roadmap_progress (employee_profile_id, roadmap_id, milestone_id)
  where milestone_id is not null and action_id is null;

create unique index if not exists roadmap_progress_unique_action
  on public.roadmap_progress (employee_profile_id, roadmap_id, action_id)
  where action_id is not null;

create table if not exists public.roadmap_versions (
  id bigint generated by default as identity primary key,
  roadmap_id bigint not null references public.career_roadmaps(id) on delete cascade,
  version_number integer not null check (version_number > 0),
  change_summary text,
  roadmap_snapshot_json jsonb not null default '{}'::jsonb,
  created_by_employee_profile_id bigint references public.employee_profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (roadmap_id, version_number)
);

create or replace function public.validate_roadmap_progress_links()
returns trigger
language plpgsql
as $$
begin
  if not exists (
    select 1
    from public.career_roadmaps roadmap
    where roadmap.id = new.roadmap_id
      and roadmap.employee_profile_id = new.employee_profile_id
  ) then
    raise exception 'roadmap_progress employee_profile_id must match the roadmap owner';
  end if;

  if new.milestone_id is not null and not exists (
    select 1
    from public.roadmap_milestones milestone
    join public.career_routes career_route on career_route.id = milestone.route_id
    where milestone.id = new.milestone_id
      and career_route.roadmap_id = new.roadmap_id
  ) then
    raise exception 'roadmap_progress milestone_id must belong to roadmap_id';
  end if;

  if new.action_id is not null and not exists (
    select 1
    from public.milestone_actions action
    join public.roadmap_milestones milestone on milestone.id = action.milestone_id
    join public.career_routes career_route on career_route.id = milestone.route_id
    where action.id = new.action_id
      and career_route.roadmap_id = new.roadmap_id
  ) then
    raise exception 'roadmap_progress action_id must belong to roadmap_id';
  end if;

  if new.action_id is not null and new.milestone_id is not null and not exists (
    select 1
    from public.milestone_actions action
    where action.id = new.action_id
      and action.milestone_id = new.milestone_id
  ) then
    raise exception 'roadmap_progress action_id must belong to milestone_id';
  end if;

  return new;
end;
$$;

create index if not exists occupation_skills_occupation_id_idx on public.occupation_skills (occupation_id);
create index if not exists occupation_skills_skill_name_idx on public.occupation_skills (lower(skill_name));
create index if not exists career_transitions_from_occupation_id_idx on public.career_transitions (from_occupation_id);
create index if not exists career_transitions_to_occupation_id_idx on public.career_transitions (to_occupation_id);
create index if not exists career_north_star_employee_profile_id_idx on public.career_north_star_settings (employee_profile_id);
create index if not exists career_north_star_target_occupation_id_idx on public.career_north_star_settings (target_occupation_id);
create index if not exists career_preferences_employee_profile_id_idx on public.career_preferences (employee_profile_id);
create index if not exists career_priority_weights_employee_profile_id_idx on public.career_priority_weights (employee_profile_id);
create index if not exists career_constraints_employee_profile_id_idx on public.career_constraints (employee_profile_id);
create index if not exists career_roadmaps_employee_profile_id_idx on public.career_roadmaps (employee_profile_id);
create index if not exists career_roadmaps_target_occupation_id_idx on public.career_roadmaps (target_occupation_id);
create index if not exists career_routes_roadmap_id_idx on public.career_routes (roadmap_id);
create index if not exists roadmap_milestones_route_id_idx on public.roadmap_milestones (route_id);
create index if not exists milestone_actions_milestone_id_idx on public.milestone_actions (milestone_id);
create index if not exists roadmap_score_components_roadmap_id_idx on public.roadmap_score_components (roadmap_id);
create index if not exists roadmap_progress_employee_profile_id_idx on public.roadmap_progress (employee_profile_id);
create index if not exists roadmap_progress_roadmap_id_idx on public.roadmap_progress (roadmap_id);
create index if not exists roadmap_progress_milestone_id_idx on public.roadmap_progress (milestone_id);
create index if not exists roadmap_progress_action_id_idx on public.roadmap_progress (action_id);
create index if not exists roadmap_versions_roadmap_id_idx on public.roadmap_versions (roadmap_id);

drop trigger if exists occupations_set_updated_at on public.occupations;
create trigger occupations_set_updated_at
before update on public.occupations
for each row execute function public.set_updated_at();

drop trigger if exists career_transitions_set_updated_at on public.career_transitions;
create trigger career_transitions_set_updated_at
before update on public.career_transitions
for each row execute function public.set_updated_at();

drop trigger if exists career_north_star_settings_set_updated_at on public.career_north_star_settings;
create trigger career_north_star_settings_set_updated_at
before update on public.career_north_star_settings
for each row execute function public.set_updated_at();

drop trigger if exists career_preferences_set_updated_at on public.career_preferences;
create trigger career_preferences_set_updated_at
before update on public.career_preferences
for each row execute function public.set_updated_at();

drop trigger if exists career_priority_weights_set_updated_at on public.career_priority_weights;
create trigger career_priority_weights_set_updated_at
before update on public.career_priority_weights
for each row execute function public.set_updated_at();

drop trigger if exists career_constraints_set_updated_at on public.career_constraints;
create trigger career_constraints_set_updated_at
before update on public.career_constraints
for each row execute function public.set_updated_at();

drop trigger if exists career_roadmaps_set_updated_at on public.career_roadmaps;
create trigger career_roadmaps_set_updated_at
before update on public.career_roadmaps
for each row execute function public.set_updated_at();

drop trigger if exists career_routes_set_updated_at on public.career_routes;
create trigger career_routes_set_updated_at
before update on public.career_routes
for each row execute function public.set_updated_at();

drop trigger if exists roadmap_milestones_set_updated_at on public.roadmap_milestones;
create trigger roadmap_milestones_set_updated_at
before update on public.roadmap_milestones
for each row execute function public.set_updated_at();

drop trigger if exists milestone_actions_set_updated_at on public.milestone_actions;
create trigger milestone_actions_set_updated_at
before update on public.milestone_actions
for each row execute function public.set_updated_at();

drop trigger if exists roadmap_score_components_set_updated_at on public.roadmap_score_components;
create trigger roadmap_score_components_set_updated_at
before update on public.roadmap_score_components
for each row execute function public.set_updated_at();

drop trigger if exists roadmap_progress_set_updated_at on public.roadmap_progress;
create trigger roadmap_progress_set_updated_at
before update on public.roadmap_progress
for each row execute function public.set_updated_at();

drop trigger if exists roadmap_progress_validate_links on public.roadmap_progress;
create trigger roadmap_progress_validate_links
before insert or update on public.roadmap_progress
for each row execute function public.validate_roadmap_progress_links();

insert into public.occupations (slug, title, family, description, seniority_level, source_label)
values
  (
    'cloud_support_engineer',
    'Cloud Support Engineer',
    'technology',
    'Supports cloud infrastructure, triages incidents, and automates repeat operational tasks.',
    'junior',
    'illustrative_seed'
  ),
  (
    'application_engineer',
    'Application Engineer',
    'technology',
    'Builds application features across frontend, backend, and platform services.',
    'mid',
    'illustrative_seed'
  ),
  (
    'data_analyst',
    'Data Analyst',
    'data',
    'Turns business data into dashboards, analysis, and decision-ready recommendations.',
    'junior',
    'illustrative_seed'
  ),
  (
    'analytics_engineer',
    'Analytics Engineer',
    'data',
    'Designs reusable analytics models, metrics, and reliable data pipelines for decision teams.',
    'mid',
    'illustrative_seed'
  ),
  (
    'project_coordinator',
    'Project Coordinator',
    'project-management',
    'Coordinates project plans, schedules, stakeholders, and delivery documentation.',
    'junior',
    'illustrative_seed'
  ),
  (
    'project_manager',
    'Project Manager',
    'project-management',
    'Owns delivery plans, risks, stakeholders, and cross-functional execution.',
    'mid',
    'illustrative_seed'
  )
on conflict (slug) do update
set
  title = excluded.title,
  family = excluded.family,
  description = excluded.description,
  seniority_level = excluded.seniority_level,
  source_label = excluded.source_label;

insert into public.occupation_skills (occupation_id, skill_name, skill_type, proficiency_level, priority, source_label)
select occupation.id, seed.skill_name, seed.skill_type, seed.proficiency_level, seed.priority, 'illustrative_seed'
from (
  values
    ('cloud_support_engineer', 'cloud', 'required', 'foundation', 5),
    ('cloud_support_engineer', 'automation', 'required', 'foundation', 4),
    ('cloud_support_engineer', 'communication', 'preferred', 'foundation', 3),
    ('application_engineer', 'typescript', 'required', 'intermediate', 5),
    ('application_engineer', 'python', 'required', 'intermediate', 4),
    ('application_engineer', 'cloud', 'preferred', 'intermediate', 3),
    ('data_analyst', 'analytics', 'required', 'foundation', 5),
    ('data_analyst', 'sql', 'required', 'foundation', 5),
    ('data_analyst', 'storytelling', 'preferred', 'foundation', 3),
    ('analytics_engineer', 'sql', 'required', 'advanced', 5),
    ('analytics_engineer', 'python', 'required', 'intermediate', 4),
    ('analytics_engineer', 'experimentation', 'preferred', 'intermediate', 3),
    ('project_coordinator', 'communication', 'required', 'foundation', 5),
    ('project_coordinator', 'project management', 'required', 'foundation', 4),
    ('project_coordinator', 'stakeholder management', 'preferred', 'foundation', 3),
    ('project_manager', 'project management', 'required', 'intermediate', 5),
    ('project_manager', 'stakeholder management', 'required', 'intermediate', 5),
    ('project_manager', 'change management', 'preferred', 'intermediate', 3)
) as seed(occupation_slug, skill_name, skill_type, proficiency_level, priority)
join public.occupations occupation on occupation.slug = seed.occupation_slug
on conflict (occupation_id, skill_name) do update
set
  skill_type = excluded.skill_type,
  proficiency_level = excluded.proficiency_level,
  priority = excluded.priority,
  source_label = excluded.source_label;

insert into public.career_transitions (
  slug,
  from_occupation_id,
  to_occupation_id,
  title,
  path_family,
  difficulty,
  estimated_months,
  rationale,
  source_label
)
select
  seed.slug,
  source_occupation.id,
  target_occupation.id,
  seed.title,
  seed.path_family,
  seed.difficulty,
  seed.estimated_months,
  seed.rationale,
  'illustrative_seed'
from (
  values
    (
      'technology_cloud_support_to_application_engineer',
      'cloud_support_engineer',
      'application_engineer',
      'Technology builder path',
      'technology',
      'moderate',
      9,
      'Illustrative transition from cloud support into application engineering using automation, Python, TypeScript, and cloud skills.'
    ),
    (
      'data_analyst_to_analytics_engineer',
      'data_analyst',
      'analytics_engineer',
      'Data platform path',
      'data',
      'moderate',
      8,
      'Illustrative transition from dashboard analysis into reusable analytics models and data pipelines.'
    ),
    (
      'project_coordinator_to_project_manager',
      'project_coordinator',
      'project_manager',
      'Project-management leadership path',
      'project-management',
      'moderate',
      6,
      'Illustrative transition from coordination responsibilities into ownership of scope, risk, stakeholders, and delivery outcomes.'
    )
) as seed(slug, from_slug, to_slug, title, path_family, difficulty, estimated_months, rationale)
join public.occupations source_occupation on source_occupation.slug = seed.from_slug
join public.occupations target_occupation on target_occupation.slug = seed.to_slug
on conflict (slug) do update
set
  from_occupation_id = excluded.from_occupation_id,
  to_occupation_id = excluded.to_occupation_id,
  title = excluded.title,
  path_family = excluded.path_family,
  difficulty = excluded.difficulty,
  estimated_months = excluded.estimated_months,
  rationale = excluded.rationale,
  source_label = excluded.source_label;
