-- Career GPS Phase 2: fields required by profile and Career North Star APIs.
-- Non-destructive migration: adds onboarding progress and a few profile metadata columns.

alter table public.career_north_star_settings
  add column if not exists career_ambition text,
  add column if not exists target_industry text,
  add column if not exists target_retirement_age integer check (
    target_retirement_age is null or (target_retirement_age >= 45 and target_retirement_age <= 80)
  );

alter table public.career_preferences
  add column if not exists risk_tolerance text check (
    risk_tolerance is null or risk_tolerance in ('low', 'moderate', 'high')
  ),
  add column if not exists learning_budget integer check (
    learning_budget is null or learning_budget >= 0
  ),
  add column if not exists preferred_company_type text,
  add column if not exists international_mobility boolean not null default false,
  add column if not exists top_priorities_json jsonb not null default '[]'::jsonb;

create table if not exists public.career_onboarding_progress (
  id bigint generated by default as identity primary key,
  employee_profile_id bigint not null unique references public.employee_profiles(id) on delete cascade,
  current_step text not null default 'north_star',
  completed_steps_json jsonb not null default '[]'::jsonb,
  is_complete boolean not null default false,
  last_completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists career_onboarding_progress_employee_profile_id_idx
  on public.career_onboarding_progress (employee_profile_id);

drop trigger if exists career_onboarding_progress_set_updated_at on public.career_onboarding_progress;
create trigger career_onboarding_progress_set_updated_at
before update on public.career_onboarding_progress
for each row execute function public.set_updated_at();
