-- Phase 7: Career Buddy conversations and messages.
-- Additive only. Run after Career GPS migrations 001 through 004.

create table if not exists public.career_buddy_conversations (
  id bigint generated by default as identity primary key,
  employee_profile_id bigint not null references public.employee_profiles(id) on delete cascade,
  roadmap_id bigint references public.career_roadmaps(id) on delete set null,
  title text not null default 'Career Buddy conversation',
  status text not null default 'active' check (status in ('active', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.career_buddy_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.career_buddy_conversations(id) on delete cascade,
  sender text not null check (sender in ('employee', 'assistant', 'system')),
  content text not null,
  structured_response_json jsonb not null default '{}'::jsonb,
  provider text not null default 'template',
  model text,
  created_at timestamptz not null default now()
);

create index if not exists idx_career_buddy_conversations_employee
  on public.career_buddy_conversations(employee_profile_id);

create index if not exists idx_career_buddy_conversations_roadmap
  on public.career_buddy_conversations(roadmap_id);

create index if not exists idx_career_buddy_messages_conversation
  on public.career_buddy_messages(conversation_id, created_at);

create or replace function public.is_career_buddy_conversation_owner(conversation_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.career_buddy_conversations c
    where c.id = conversation_id
      and public.is_employee_profile_owner(c.employee_profile_id)
  );
$$;

alter table public.career_buddy_conversations enable row level security;
alter table public.career_buddy_messages enable row level security;

drop policy if exists "career_buddy_conversations_employee_select" on public.career_buddy_conversations;
create policy "career_buddy_conversations_employee_select"
  on public.career_buddy_conversations
  for select
  to authenticated
  using (public.is_employee_profile_owner(employee_profile_id));

drop policy if exists "career_buddy_conversations_employee_insert" on public.career_buddy_conversations;
create policy "career_buddy_conversations_employee_insert"
  on public.career_buddy_conversations
  for insert
  to authenticated
  with check (public.is_employee_profile_owner(employee_profile_id));

drop policy if exists "career_buddy_conversations_employee_update" on public.career_buddy_conversations;
create policy "career_buddy_conversations_employee_update"
  on public.career_buddy_conversations
  for update
  to authenticated
  using (public.is_employee_profile_owner(employee_profile_id))
  with check (public.is_employee_profile_owner(employee_profile_id));

drop policy if exists "career_buddy_messages_employee_select" on public.career_buddy_messages;
create policy "career_buddy_messages_employee_select"
  on public.career_buddy_messages
  for select
  to authenticated
  using (public.is_career_buddy_conversation_owner(conversation_id));

drop policy if exists "career_buddy_messages_employee_insert" on public.career_buddy_messages;
create policy "career_buddy_messages_employee_insert"
  on public.career_buddy_messages
  for insert
  to authenticated
  with check (public.is_career_buddy_conversation_owner(conversation_id));
